# Nom pour le workflow
name: Deuxième workflow
# On précise quel est le déclencheur de notre worflow
on: push
# On pércise les actions à réaliser lors du déclenchement de ce workflow
jobs:
  # Définition de la première action à réaliser
  premier-job:
    name: premier job
    # On précise le système d'exploitation
    runs-on: ubuntu-latest
    # On écrit ici les étapes pour notre action
    steps:
    # On donne un nom à notre étape & une commande
      - name: Dit Bienvenue
        run: echo "Bienvenue dans la CI/CD pour l'API de satisfaction !"
      - name: Affiche date du déclenchement
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Affiche heure du déclenchement
        run: echo "Goodbye" 
