# Nom pour le workflow
name: Troisième workflow
on: 
  - push
  - pull_request
jobs:
  premier-job:
    name: build de l'application
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4
      - name: Configuration Python 3.11.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.9"
      - name: Installation des dépendances
        run: pip install -r requirements.txt
      - name: test
        run: python test_app_satisfaction.py